name:                mars-rover
version:             0.1.0.0
github:              github.com/jayaramsankara/mars-rover
license:             BSD3
author:              jayaramsankara
maintainer:          jayaramsankara
copyright:           2017 Jayaram Sankaranarayanan

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/mars-rover#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mars-rover-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mars-rover

tests:
  mars-rover-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mars-rover
